version: '3.8'
services:
  db:
    container_name: db
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDAT: /var/lib/postgresql/data
    volumes:
      - ./postgre:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APP_DIRECTORY}:/code
      - ${VHOST_PATH}:/etc/nginx/conf.d
    links:
      - php
  php:
    container_name: php
    links:
      - db
    build:
      context: ./php
      args:
        - XDEBUG=${APP_XDEBUG}
    volumes:
      - ${APP_DIRECTORY}:/code
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# node:
# rabbitmq: